### ISSUE TITLE
Trim branches

### ISSUE THREAD

**Issue by phentos** [tritonhacks/Tritonhack2024-ML-Starter-Kit#23]
Of the [11 outstanding branches](https://github.com/tritonhacks/Tritonhack2024-ML-Starter-Kit/branches), 
- 9 have already been merged. Unless further work is intended, recommend deleting them
- [sunwoo604-patch-1](https://github.com/tritonhacks/Tritonhack2024-ML-Starter-Kit/tree/sunwoo604-patch-1) lacks a PR and hasn't seen much activity; recommend complete and/or delete
- #2 was ready to merge in Feb but conflicts have been created since; recommend resolve + merge and/or delete

**Comment by sunwoo604** [comment]
Done
