### ISSUE TITLE
Documentation is in gdocs instead of github

### ISSUE THREAD

**Issue by phentos** [tritonhacks/Tritonhack2024-ML-Starter-Kit#3]
Suggested migration destinations:
1. [Wiki](https://github.com/tritonhacks/Tritonhack2024-ML-Starter-Kit/wiki). This is an awesome tool, especially for our use case. Migrating to a wiki would let you isolate different aspects (instruction, planning, responsibilities, etc) while still acting as a lower-burden "work in progress" format. Note: the wiki is specific to the repo's webpage -- it won't accompany it during clones/pulls/forks. 
2. Markdown. Ideal for setup instructions especially. It accompanies the code and is natively visible in the same IDE they work in.

**Comment by sunwoo604** [comment]
> Suggested migration destinations:
> 
> 1. [Wiki](https://github.com/tritonhacks/Tritonhack2024-ML-Starter-Kit/wiki). This is an awesome tool, especially for our use case. Migrating to a wiki would let you isolate different aspects (instruction, planning, responsibilities, etc) while still acting as a lower-burden "work in progress" format. Note: the wiki is specific to the repo's webpage -- it won't accompany it during clones/pulls/forks.
> 2. Markdown. Ideal for setup instructions especially. It accompanies the code and is natively visible in the same IDE they work in.

Hi, since I set the ruleset where every merge request should be reviewed by a peer(so the group members can learn about git and development environment), I decided to write everything on the google doc first and then make index.md so we can publish instructions like a website. There is one student who is working on that as well so it will be there by the time we are done with the project. Thank you

**Comment by totally-not-frito-lays** [comment]
One way you can get around that is by making a feature branch, committing all the changes there, then once the feature is complete (in this case, documentation), set up a PR where the review happens.

Alternatively, the [wiki](https://github.com/tritonhacks/Tritonhack2024-ML-Starter-Kit/wiki) is available for commits without review.

Happy to see progress being made!
